/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursework;

import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GS
 */
public class Moto extends javax.swing.JFrame {  
    
    /**
     * Creates new form Moto
     */
    public Moto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ID_FIELD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BRAND_FIELD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PRICE_FIELD = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        Clear_Button = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sortComboBox = new javax.swing.JComboBox<>();
        Search_Field = new javax.swing.JTextField();
        Search_Button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Open_FileItem = new javax.swing.JMenuItem();
        ExitItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        UserManulItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rossi MotoCorp LTD");
        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        ID_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_FIELDActionPerformed(evt);
            }
        });
        ID_FIELD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ID_FIELDKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID    :");

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("SPECIFICATION    :");

        BRAND_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRAND_FIELDActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("BRAND NAME    :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select A Category", "Cruiser", "Sports", "Touring", "Dirt", "Naked" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("CATEGORY    :");

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("PRICE    :");

        PRICE_FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRICE_FIELDActionPerformed(evt);
            }
        });
        PRICE_FIELD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PRICE_FIELDKeyPressed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("ABS");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Non-ABS");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/Image/—Pngtree—neon sport motorcycle logo_6557376.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        Clear_Button.setBackground(new java.awt.Color(0, 255, 255));
        Clear_Button.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        Clear_Button.setText("CLEAR");
        Clear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_ButtonActionPerformed(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(255, 0, 51));
        AddButton.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BRAND_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ID_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PRICE_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Clear_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BRAND_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRICE_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bike ID", "Brand Name", "Category", "Specification", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        sortComboBox.setBackground(new java.awt.Color(0, 255, 255));
        sortComboBox.setFont(new java.awt.Font("Unispace", 0, 10)); // NOI18N
        sortComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort BY : ", "Bike ID", "Specification" }));
        sortComboBox.setBorder(null);
        sortComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortComboBoxActionPerformed(evt);
            }
        });

        Search_Field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Search_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_FieldActionPerformed(evt);
            }
        });
        Search_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Search_FieldKeyPressed(evt);
            }
        });

        Search_Button.setBackground(new java.awt.Color(255, 0, 0));
        Search_Button.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        Search_Button.setForeground(new java.awt.Color(255, 255, 255));
        Search_Button.setText("Search");
        Search_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ButtonActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Search Price");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Search_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(sortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(Search_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ROSSI MotoCORP LTD.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 342, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jMenu1.setText("File");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });

        Open_FileItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/Image/icons8_archive_folder_15px.png"))); // NOI18N
        Open_FileItem.setText("Open Existing File");
        Open_FileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_FileItemActionPerformed(evt);
            }
        });
        jMenu1.add(Open_FileItem);

        ExitItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/Image/icons8_delete_15px.png"))); // NOI18N
        ExitItem.setText("Exit");
        ExitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitItemActionPerformed(evt);
            }
        });
        jMenu1.add(ExitItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        UserManulItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework/Image/icons8_refer_to_manual_15px.png"))); // NOI18N
        UserManulItem.setText("Manual");
        UserManulItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserManulItemActionPerformed(evt);
            }
        });
        jMenu2.add(UserManulItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void PRICE_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRICE_FIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRICE_FIELDActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BRAND_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRAND_FIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BRAND_FIELDActionPerformed

    private void ID_FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_FIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_FIELDActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void PRICE_FIELDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PRICE_FIELDKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(Character.isLetter(c))
        {
             PRICE_FIELD.setEditable(false);
             
             JOptionPane.showMessageDialog(null,"Enter Numbers Only.", "Invalid Input",JOptionPane.ERROR_MESSAGE);
        }else
        {
            PRICE_FIELD.setEditable(true);
        }
        
    }//GEN-LAST:event_PRICE_FIELDKeyPressed

    private void ID_FIELDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ID_FIELDKeyPressed
        // TODO add your handling code here:
         char c =evt.getKeyChar();
        if(Character.isLetter(c))
        {
             ID_FIELD.setEditable(false);
             
             JOptionPane.showMessageDialog(null,"Enter number Only.", "Invalid Input",JOptionPane.ERROR_MESSAGE);
        }else
        {
            ID_FIELD.setEditable(true);
        }
        
    }//GEN-LAST:event_ID_FIELDKeyPressed
 
    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        
    }//GEN-LAST:event_jMenu1MenuSelected

    private void Clear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_ButtonActionPerformed
        // TODO add your handling code here:
        BRAND_FIELD.setText(null);
        ID_FIELD.setText(null);
        PRICE_FIELD.setText(null);
        jComboBox1.setSelectedItem("Select A Category");       
    }//GEN-LAST:event_Clear_ButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        String BikeID=ID_FIELD.getText();
        String BrandName=BRAND_FIELD.getText();
        String Category = jComboBox1.getSelectedItem().toString();
        String Specs = "";        
        String Price = PRICE_FIELD.getText();       
        
        if(jRadioButton3.isSelected())
        {  
        Specs = "ABS";
        }
        if(jRadioButton4.isSelected())
        {  
        Specs = "Non-ABS";
        }
        
        if(BikeID.equals("") || BrandName.equals("") || Category.equals("Select A Category") || Price.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please fill all the fields.", "Empty Field!",JOptionPane.ERROR_MESSAGE);
        }
        else{
        DefaultTableModel model =  (DefaultTableModel)jTable1.getModel();
        model.insertRow(jTable1.getRowCount(),new Object[]{"","","","",""});
        String[]values={BikeID,BrandName,Category,Specs,Price};
        int rowCount=jTable1.getRowCount();
        int columnCount=jTable1.getColumnCount();
        int rowIndex=0;
        do
        {
            String s=(String)jTable1.getValueAt(rowIndex, 0);
            if(s!=null && s.length()!=0)
            {
                rowIndex++;
            }
            else
            {
                break;
            }
        }
        while(rowIndex<rowCount);
        for(int i=0;i<columnCount;i++)
        {
                jTable1.setValueAt(values[i], rowIndex, i);
        
        }
        JOptionPane.showMessageDialog(null,"Data inserted");
        }
        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void sortComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortComboBoxActionPerformed
        // TODO add your handling code here:
        int selected = sortComboBox.getSelectedIndex();
        if (selected == 1) {
            sort(0,0);
        } else if(selected == 2){
            sort(0,3);       
        }
    }      
    //Sorting
    public void sort(int order, int column) {
        // count the total number of rows with value        
        int countRow = jTable1.getRowCount();
        int Count = jTable1.getRowCount();        
        // Creating a new array with size count
        Object[] a = new Object[Count];
        // Storing the table value in array a
        // by traversing through table data
        int rowCount = jTable1.getRowCount();
        for (int i = 0; i < Count; i++) {
            String Bike_ID = (String) jTable1.getValueAt(i, column);
            a[i] = Bike_ID;
        }
        for (int i = 0; i < a.length; i++) {
            int min = i;
            for (int j = i + 1; j < a.length; j++) {
                 
                if (order == 0) {
                    if (a[j].toString().compareTo(a[min].toString())<0) {
                        min = j;
                    }
                } else {
                    if (a[j].toString().compareTo(a[min].toString())>0) {
                        min = j;
                    }
                }
            }            
            // swapping array values
            Object temp = a[min];
            a[min] = a[i];
            a[i] = temp;
                
            Swap(i,min);
        }
    }
    
    //method for Swapping the values
    public void Swap(int i, int min){
            // swapping BIKEID values
            String ID = (String) jTable1.getValueAt(i, 0);
            jTable1.setValueAt(jTable1.getValueAt(min, 0), i, 0);
            jTable1.setValueAt(ID, min, 0);
            
            // swapping BrandName values
            String NAME = (String) jTable1.getValueAt(i, 1);
            jTable1.setValueAt(jTable1.getValueAt(min, 1), i, 1);
            jTable1.setValueAt(NAME, min, 1);
            
            // swapping Category values
            String Cate = (String) jTable1.getValueAt(i, 2);
            jTable1.setValueAt(jTable1.getValueAt(min, 2), i, 2);
            jTable1.setValueAt(Cate, min, 2);
            
            // swapping Specification values
            String Specs = (String) jTable1.getValueAt(i, 3);
            jTable1.setValueAt(jTable1.getValueAt(min, 3), i, 3);
            jTable1.setValueAt(Specs, min, 3);
            
            // swapping Price values
            String Price = (String) jTable1.getValueAt(i, 4);
            jTable1.setValueAt(jTable1.getValueAt(min, 4), i, 4);
            jTable1.setValueAt(Price, min, 4);  
    }//GEN-LAST:event_sortComboBoxActionPerformed

    private void Search_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ButtonActionPerformed
        // TODO add your handling code here:
        String SearchPrice=Search_Field.getText();
        if(SearchPrice.equals("")){
        JOptionPane.showMessageDialog(null,"Enter a value before searching!.", " Error!",JOptionPane.ERROR_MESSAGE);            
        } 
        else
        {
        ArrayList<Integer> ID_Array = new ArrayList();
        ArrayList<String> Name_Array= new ArrayList();
        ArrayList<String> Category_Array = new ArrayList();
        ArrayList<String> Specs_Array = new ArrayList();
        ArrayList<Integer> Price_Array = new ArrayList();
        
        int rowCount = jTable1.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            String bikeid = (String) jTable1.getValueAt(i, 0);
            String bikename = (String) jTable1.getValueAt(i, 1);
            String bikecate = (String) jTable1.getValueAt(i, 2);
            String bikespecs = (String) jTable1.getValueAt(i, 3);
            String bikeprice = (String) jTable1.getValueAt(i, 4);
            if(bikeid != null && bikename != null && bikecate!=null&& bikespecs!=null&& bikeprice!=null){
                ID_Array.add(Integer.parseInt(bikeid));
                Name_Array.add(bikename);
                Category_Array.add(bikecate);
                Specs_Array.add(bikespecs);
                Price_Array.add(Integer.parseInt(bikeprice));
            }
        }
        for (int i = 0; i < Price_Array.size(); i++) {
            int min = i;
            for (int j = i + 1; j < ID_Array.size(); j++) {
               
                    if (Price_Array.get(j) < Price_Array.get(min)) {
                        min = j;
                    }
                }
            // Swapping array values
            int Id_Temp = ID_Array.get(min);
            ID_Array.set(min, ID_Array.get(i));
            ID_Array.set(i, Id_Temp);

            String Name_Temp = Name_Array.get(min);
            Name_Array.set(min, Name_Array.get(i));
            Name_Array.set(i, Name_Temp);

            String Category_Temp = Category_Array.get(min);
            Category_Array.set(min, Category_Array.get(i));
            Category_Array.set(i, Category_Temp);
            
            String Specification_Temp = Specs_Array.get(min);
            Specs_Array.set(min, Specs_Array.get(i));
            Specs_Array.set(i, Specification_Temp);
            
            int Price_Temp = Price_Array.get(min);
            Price_Array.set(min, Price_Array.get(i));
            Price_Array.set(i,Price_Temp);   
    }        
        int value = Integer.parseInt(Search_Field.getText());
        int low = 0;
        int high = Price_Array.size()-1;
        int output = Search(Price_Array, low, high, value);
        
        if(output == -1){
            JOptionPane.showMessageDialog(null,"The entered price is not found.", "Matching Error!",JOptionPane.ERROR_MESSAGE);
        }else{
            int getID = ID_Array.get(output);
            String getName = Name_Array.get(output);
            String getCategory = Category_Array.get(output);
            String getSpecs = Specs_Array.get(output);
            int getPrice = Price_Array.get(output);
            String BikeDetail = "Bike ID: "+getID+"\n"+"Brand Name: "+getName+"\n"+ "Category: "+getCategory +"\n"+ "Specification : "+getSpecs;
            JOptionPane.showMessageDialog(null,BikeDetail, "Price Found.", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_Search_ButtonActionPerformed
    
    public int Search(ArrayList<Integer> a, int low, int high, int value){
        int mid = (low+high)/2;
        if(low>high){
            return -1;
        }
        if(a.get(mid) == value){
            return mid;
        }else if(value<a.get(mid)){
            return Search(a, low, mid-1, value);
        }else{
            return Search(a, mid+1, high, value);
        }
    }
    private void Search_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_FieldActionPerformed
    
    
    private void Search_FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_FieldKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(Character.isLetter(c))
        {
             Search_Field.setEditable(false);
             
             JOptionPane.showMessageDialog(null,"Enter Numbers Only.", "Invalid Input",JOptionPane.ERROR_MESSAGE);
        }else
        {
             Search_Field.setEditable(true);
        }
    }//GEN-LAST:event_Search_FieldKeyPressed

    private Component f;
    private void Open_FileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_FileItemActionPerformed
        // TODO add your handling code here:
        
        String filePath = "text123.csv";
        File file =new File (filePath);
       try{
         BufferedReader br = new BufferedReader(new FileReader(file));
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
         
         Object [] tableLines=br.lines().toArray();
         
         for (int i=0 ; i< tableLines.length; i++){
             String line = tableLines[i].toString().trim();
             String[] dataRow = line.split(",");
             model.addRow(dataRow);
             {
                 Component f = null;
                      
                 
             }
            
         }
          JOptionPane.showMessageDialog(f,"Data Successfully Imported");
       }
       catch(Exception Ex)
       {
           
       }
    }//GEN-LAST:event_Open_FileItemActionPerformed

    private void ExitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitItemActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitItemActionPerformed

    private void UserManulItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserManulItemActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
    }//GEN-LAST:event_UserManulItemActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Moto().setVisible(true);                
            }         
        });         
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField BRAND_FIELD;
    private javax.swing.JButton Clear_Button;
    private javax.swing.JMenuItem ExitItem;
    private javax.swing.JTextField ID_FIELD;
    private javax.swing.JMenuItem Open_FileItem;
    private javax.swing.JTextField PRICE_FIELD;
    private javax.swing.JButton Search_Button;
    private javax.swing.JTextField Search_Field;
    private javax.swing.JMenuItem UserManulItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> sortComboBox;
    // End of variables declaration//GEN-END:variables
    
 
}
    
    
    


